# Generated by Django 3.1.3 on 2020-11-18 01:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_no', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('1', 'General'), ('2', 'Management'), ('3', 'Compensation'), ('4', 'Suggestions'), ('5', 'Complaint')], default='1', max_length=10)),
                ('email', models.CharField(max_length=150, validators=[django.core.validators.EmailValidator(whitelist=['ems']), django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(100), feedback.models.validate_allowed_domains])),
                ('comment', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
