# Generated by Django 3.1.3 on 2020-11-11 02:08

import django.core.validators
from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=150, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(20), feedback.models.validate_allowed_domains]),
        ),
    ]
