# Generated by Django 3.1.3 on 2020-11-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
