# Generated by Django 3.1.3 on 2020-11-18 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='emp_no',
            field=models.ForeignKey(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, related_name='employeeSalaries', to='myems.employee'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='emp_no',
            field=models.ForeignKey(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, related_name='employeeTitles', to='myems.employee'),
        ),
    ]
