# Generated by Django 3.1.3 on 2020-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0002_auto_20201111_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(related_name='departments', through='myems.DeptEmp', to='myems.Department'),
        ),
    ]
