# Generated by Django 3.1.3 on 2020-11-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0003_auto_20201118_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dg',
            name='id',
        ),
        migrations.AddField(
            model_name='dg',
            name='sn',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
