# Generated by Django 3.1.3 on 2020-11-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0003_employee_departments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salaries',
            new_name='Salary',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='salary',
            new_name='salary_amount',
        ),
    ]
