# Generated by Django 3.1.3 on 2020-11-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0004_auto_20201111_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
