# Generated by Django 3.1.3 on 2020-11-12 07:29

from django.db import migrations
import myems.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0005_auto_20201112_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=stdimage.models.StdImageField(blank=True, max_length=255, null=True, storage=myems.models.LocalFileSystemStorage(), upload_to=myems.models.upload_path_handler),
        ),
    ]
