# Generated by Django 3.1.3 on 2020-11-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0005_auto_20201119_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ib_admin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ib_putaway',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ib_unstuffing',
            field=models.IntegerField(),
        ),
    ]
